apps/node/urls.py
from django.urls import path

from .views import SelectNode, NodeView, DetailView

urlpatterns = [
    path('node/', NodeView.as_view(), name='node-all'),
    path('node/<int:n_id>/', NodeView.as_view(), name='node-per'),
    path('node/detail/<int:n_id>/', DetailView.as_view(), name='node-detail')
]

ssrmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from users.views import Index, Activate
# from ssrmgmt.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('activate/', Activate.as_view()),
    path('api/<str:version>/', include(('users.urls', 'users'), namespace='users')),
    path('api/<str:version>/', include(('API.urls', 'API'), namespace='api')),
    path('api/<str:version>/', include(('node.urls', 'node'), namespace='node')),
    path('', Index.as_view(), name='index'),
    # 创建一个命名空间，可以有效的对url进行分类
    # path('users/', include(("users.urls", "users"), namespace="users")),
    # path('api/', include(("API.urls", "API"), namespace="api")),
    # path('node/', include(("node.urls", "node"), namespace="node")),
    # path('media/<str>', serve, {"document_root": MEDIA_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend/usage/nodedetail.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-节点详情</title>
{% endblock %}

{% block other_link %}
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    <script src="{% static 'lib/chart-master/Chart.js' %}"></script>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper site-min-height">
            <h3><i class="fa fa-angle-right"></i> 节点详细信息 </h3>
            <!-- page start-->
            <div class="row mt">
                <div class="col-lg-4 col-md-4 col-sm-4 mb">
                    <div class="weather-3 pn centered" style="background: #b3daff;">
                        <i class="fa fa-male"></i>
                        <h1>{{ user.online_rate }} %</h1>
                        <div class="info">
                            <div class="row">
                                <h3 class="centered">在线率</h3>
                                <div class="col-sm-6 col-xs-6 pull-left">
                                    <p class="goleft"><i class="fa fa-tint"></i> {{ user.total }} Total</p>
                                </div>
                                <div class="col-sm-6 col-xs-6 pull-right">
                                    <p class="goright"><i class="fa fa-flag"></i> {{ user.online }} Online</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 mb">
                    <!-- WHITE PANEL - TOP USER -->
                    <div class="white-panel pn">
                        <div class="white-header">
                            <h5>暂时不用</h5>
                        </div>
                        <!--<p><img src="img/ui-zac.jpg" class="img-circle" width="50"></p>-->
                        <p><b>Zac Snider</b></p>
                        <div class="row">
                            <div class="col-md-6">
                                <p class="small mt">占位</p>
                                <p>2012</p>
                            </div>
                            <div class="col-md-6">
                                <p class="small mt">占位</p>
                                <p>$ 47,60</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 mb">
                    <div class="grey-panel pn donut-chart">
                        <div class="grey-header">
                            <h5>暂时不用</h5>
                        </div>
                        <canvas id="serverstatus01" height="120" width="120"></canvas>
                        <script>
                            var doughnutData = [{
                                value: 70,
                                color: "#FF6B6B"
                            },
                                {
                                    value: 30,
                                    color: "#fdfdfd"
                                }
                            ];
                            var myDoughnut = new Chart(document.getElementById("serverstatus01").getContext("2d")).Doughnut(doughnutData);
                        </script>
                        <div class="row">
                            <div class="col-sm-6 col-xs-6 goleft">
                                <p>Usage<br/>Increase:</p>
                            </div>
                            <div class="col-sm-6 col-xs-6">
                                <h2>21%</h2>
                            </div>
                        </div>
                    </div>
                    <!-- /grey-panel -->
                </div>
            </div>
            <div class="row mt">
                <div class="col-lg-12">
                    <div class="content-panel">
                        <h4><i class="fa fa-angle-right"></i> 节点流量使用情况 </h4>
                        <div class="panel-body">
                            <div id="hero-area" class="graph"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- page end-->
        </section>
    </section>
{% endblock %}

{% block otherscript %}
    <script src="{% static "lib/raphael/raphael.min.js" %}"></script>
    <script src="{% static "lib/morris/morris.min.js" %}"></script>
    <script type="text/javascript">
        var Script = function () {
            $(function () {
                Morris.Area({
                    element: 'hero-area',
                    data: [
                        {% for data in usages %}
                            {
                                day: "{{ data.x|date:"Y-m-d" }}",
                                download: {{ data.yd }},
                                upload: {{ data.yu }},
                                total: {{data.yd}}+{{ data.yu }}
                            },
                        {% endfor %}
                    ],
                    xkey: 'day',
                    ykeys: ['download', 'upload', 'total'],
                    labels: ['下载(m)', '上传(m)', '总使用(m)'],
                    /*xLabelFormat: function (d) {
                        if (d.day % 3 === 0) {
                            return d
                        } else {
                            return ""
                        }
                    },*/
                    //xLabelAngle: 45,
                    hideHover: 'auto',
                    lineWidth: 1,
                    pointSize: 5,
                    lineColors: ['#4a8bc2', '#ff6c60', '#a9d86e'],
                    fillOpacity: 0.5,
                    smooth: true,
                    parse_time: false
                });
                $('.code-example').each(function (index, el) {
                    eval($(el).text());
                });
            });
        }();
    </script>
{% endblock %}

templates/backend/usage/nodelist.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-节点列表</title>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <!-- row -->
            <div class="row mt mb">
                <div class="col-md-12">
                    <section class="task-panel tasks-widget">
                        <div class="panel-heading">
                            <div class="pull-left">
                                <h5><i class="fa fa-tasks"></i> SSR-节点列表</h5>
                            </div>
                            <br>
                        </div>
                        <div class="panel-body">
                            <div class="task-content">
                                <ul id="sortable" class="task-list">
                                    <li class=""
                                        style="color: #383d41;background-color: #d9edf7;border-color: #d6d8db;">
                                        <div class="row task-title">
                                            <div class="col-md-3 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">节点名</span></div>
                                            <div class="col-md-2 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">节点IP</span></div>
                                            <div class="col-md-1 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">节点人数</span></div>
                                            <div class="col-md-2 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">节点状态</span></div>
                                            <div class="col-md-2 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">节点详情</span></div>
                                            <div class="col-md-2 col-sm-6"><span
                                                    style="font-size: medium;font-weight: bold">选择节点</span></div>
                                        </div>
                                    </li>
                                    {% for foo in node_info %}
                                        <li class="list-primary">
                                            <div class="row task-title" style="font-weight: bold">
                                                <div class="col-md-3 col-sm-6">{{ foo.node.name }}</div>
                                                <div class="col-md-2 col-sm-6">{{ foo.node.ip }}</div>
                                                <div class="col-md-1 col-sm-6"><i class="fa fa-male">{{ foo.count }}</i></div>
                                                <div class="col-md-2 col-sm-6">
                                                    {% if foo.status == 'online' %}
                                                        <span class="badge bg-theme">online</span>
                                                    {% else %}
                                                        <span class="badge bg-important">offline</span>
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-2 col-sm-6">
                                                    <a class="btn btn-link btn-xs fa fa-bar-chart-o"
                                                            href="{% url 'node:node-detail' foo.node.node_id %}"></a>
                                                </div>
                                                <div class="col-md-2 col-sm-6">
                                                    {% if curr_node.node_id == foo.node.node_id %}
                                                        当前节点
                                                    {% else %}
                                                        <button class="btn btn-success btn-xs fa fa-check"
                                                                onclick="select_node({{ foo.node.node_id }})"></button>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class=" add-task-row">
                                <a class="btn btn-success btn-sm pull-left" href="{% url 'node:node-show' %}">刷新</a>
                            </div>
                        </div>
                    </section>
                </div>
                <!--/col-md-12 -->
            </div>
            <!-- /row -->
        </section>
    </section>
{% endblock %}

{% block otherscript %}
    <script type="text/javascript">
        function select_node(n_id) {
            csrf = '{{ csrf_token }}';
            //发起ajax请求，注意csrf攻击
            $.post("{% url 'node:node-select' %}", {
                'csrfmiddlewaretoken': csrf,
                'n_id': n_id
            }, function (data) {
                //获取返回的数据并进行操作
                alert(data.res);
            })
        }
    </script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="{% static 'lib/tasks.js' %}" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function () {
            TaskList.initTaskWidget();
        });

        $(function () {
            $("#sortable").sortable();
            $("#sortable").disableSelection();
        });
    </script>
{% endblock %}

templates/backend/usage/tutorial.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-使用教程</title>
{% endblock %}

{% block main_content %}
        <section id="main-content">
        <section class="wrapper">
            <div class="col-lg-12 mt">
                <div class="row content-panel">
                    <div class="col-lg-10 col-lg-offset-1">
                        <div class="invoice-body">
                            <div class="pull-left">
                                <h1>SSRMGMT使用教程</h1>
                                <address>
                                    <strong>dongdawang</strong><br>
                                </address>
                                <h3>1. 下载客户端</h3>
                                <p>
                                    去https://shadowsocks.org/en/download/clients.html网站中选择合适的客户端下载下来，然后安装
                                </p>
                                <h3>2. 配置SSR账号</h3>
                                <p>
                                    在[我的]-[资料编辑中]找到修改SSR账号信息<br>
                                    如果你不知道SSR账号各项参数的意思可以以以下配置，配置SSR账号，<br>
                                    <img src="{{ MEDIA_URL }}image/ssrconf.PNG" width="500" height="500"><br>
                                    上图中如果你使用的是shadowsocksr客户端请把兼容原版勾选上。
                                </p>
                                <h3>3. 客户端使用</h3>
                                <p>
                                    在账号配置好了之后，在[我的]-[用户中心]中可以看到账号的SS二维码和链接，SSR二维码和链接。<br>
                                    它们分别对应SS客户端和SSR客户端。点击复制链接可以直接将链接复制。<br>
                                    右键客户端打开如下界面，然后可以选择[从剪切板导入url], [扫面屏幕上的二维码]两种导入配置的方式。<br>
                                    任意选择一种即可<br>
                                    <img src="{{ MEDIA_URL }}image/ssrclient.PNG">
                                </p>
                                <h3>4. 验证</h3>
                                <p>
                                    最后打开浏览器输入www.google.com查看是否可以打开。<br>
                                    <img src="{{ MEDIA_URL }}image/google.PNG"><br>
                                </p>
                            </div>
                            <!-- /col-lg-10 -->
                            <br>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
            <!--/col-lg-12 mt -->
        </section>

        <!-- /wrapper -->
    </section>

{% endblock %}