apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import logout
from django.conf import settings

from .views import (SendEmailCode, System, Activate, ResetPwd,
                    AccountEdit, AccountProfilePhotoModify, AccountPwdModify, AccountGeneralModify, ResetPwdEmail,
                    AccountNameModify, AccountSSRModify, AccountEmailModify, ProfileCenter,
                    WorkOrderShow, WorkOrderAdd, WorkorderView, WorkorderDelete, BuyTime, TradeRecodeShow,
                    Tutorial)

from users.utils.auth.views import ObtainJWTView, RefreshJWTView
from .views import (RegisterView, ProfileView, SSRAccountView, OnlineIPView, DataUsageView,
                    ProfilePhotoView)

urlpatterns = [
    path('login/', ObtainJWTView.as_view(), name='login'),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name="logout"),
    path('refresh/', RefreshJWTView.as_view()),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('ssr/', SSRAccountView.as_view(), name='ssr'),
    path('onlineip/', OnlineIPView.as_view(), name='onelineip'),
    path('datausage/', DataUsageView.as_view(), name='datausage'),
    path('profilephoto/', ProfilePhotoView.as_view(), name='profilephoto'),

    path('resetpwd/', ResetPwd.as_view(), name='resetpwd'),
    path('resetpwdemail/', ResetPwdEmail.as_view(), name='resetpwdemail'),
    path('system/', System.as_view(), name='system'),
    path('profile/send-mail', SendEmailCode.as_view(), name='send_mail'),
    path('profile/account_edit', AccountEdit.as_view(), name='account_edit'),
    path('account/profile_photo_modify', AccountProfilePhotoModify.as_view(), name="photo_modify"),
    path('account/modify-pwd', AccountPwdModify.as_view(), name='modify-pwd'),
    path('account/modify-general', AccountGeneralModify.as_view(), name='modify-general'),
    path('account/modify-username', AccountNameModify.as_view(), name='modify-username'),
    path('account/modify-ssr', AccountSSRModify.as_view(), name='modify-ssr'),
    path('account/modify-email', AccountEmailModify.as_view(), name='modify-email'),
    path('profile/center', ProfileCenter.as_view(), name='profile-center'),
    path('workorder/show', WorkOrderShow.as_view(), name='workorder-show'),
    path('workorder/add', WorkOrderAdd.as_view(), name='workorder-add'),
    path('workorder/delete/<int:wo_id>', WorkorderDelete.as_view(), name='workorder-delete'),
    path('workorder/view/<int:wo_id>', WorkorderView.as_view(), name='workorder-view'),
    path('buy/time', BuyTime.as_view(), name='buy-time'),
    path('buy/recordshow', TradeRecodeShow.as_view(), name='record-show'),
    path('usage/tutorial/', Tutorial.as_view(), name='tutorial')
]

ssrmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from users.views import Index, Activate
# from ssrmgmt.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('activate/', Activate.as_view()),
    path('api/<str:version>/', include(('users.urls', 'users'), namespace='users')),
    path('api/<str:version>/', include(('API.urls', 'API'), namespace='api')),
    path('api/<str:version>/', include(('node.urls', 'node'), namespace='node')),
    path('', Index.as_view(), name='index'),
    # 创建一个命名空间，可以有效的对url进行分类
    # path('users/', include(("users.urls", "users"), namespace="users")),
    # path('api/', include(("API.urls", "API"), namespace="api")),
    # path('node/', include(("node.urls", "node"), namespace="node")),
    # path('media/<str>', serve, {"document_root": MEDIA_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend/bebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    {% block title %}<title>主页</title>{% endblock %}

    <!-- Favicons -->
    <link href="{% static "img/favicon.png" %}" rel="icon">
    <link href="{% static "img/apple-touch-icon.png" %}" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static "lib/font-awesome/css/font-awesome.css" %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/zabuto_calendar.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "lib/gritter/css/jquery.gritter.css" %}"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
    <script src="{% static "lib/chart-master/Chart.js" %}"></script>
    {% block other_link %}{% endblock %}
</head>

<body>
<section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="{% url 'index' %}" class="logo"><b><span>SSR</span>MGMT</b></a>
        <!--logo end-->
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
        </div>
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <p class="centered"><a href="{% url 'users:profile-show' %}"><img
                        src="{{ MEDIA_URL }}{{ request.user.profile_photo }}" class="img-circle" width="80"></a>
                </p>
                <h5 class="centered">{{ request.user.username }}</h5>
                <li class="mt">
                    <a id="as-system" href="{% url 'users:system' %}">
                        <i class="fa fa-cogs"></i>
                        <span>系统</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a id="as-my" href="javascript:;">
                        <i class="fa fa-user"></i>
                        <span>我的</span>
                    </a>
                    <ul class="sub">
                        <li><a id="as-center" href="{% url 'users:profile-center' %}">用户中心</a></li>
                        <li><a id="as-account" href="{% url 'users:profile-show' %}">账户资料</a></li>
                        <li><a id="as-edit" href="{% url 'users:account_edit' %}">资料编辑</a></li>
                        <li><a id="as-workorder" href="{% url 'users:workorder-show' %}">用户工单</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a id="as-coin" href="javascript:;">
                        <i class="fa fa-money"></i>
                        <span>硬币</span>
                    </a>
                    <ul class="sub">
                        <li><a id="as-answer" href="#">答题赚取硬币</a></li>
                        <li><a id="as-invite" href="#">邀请赚取硬币</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a id="as-buy" href="javascript:;">
                        <i class="fa fa-suitcase"></i>
                        <span>购买</span>
                    </a>
                    <ul class="sub">
                        <li><a id="as-time" href="{% url 'users:buy-time' %}">购买时长</a></li>
                        <li><a id="as-record" href="{% url 'users:record-show' %}">购买记录</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a id="as-use" href="javascript:;">
                        <i class="fa fa-tasks"></i>
                        <span>使用</span>
                    </a>
                    <ul class="sub">
                        <li><a id="as-list" href="{% url 'node:node-show' %}">节点列表</a></li>
                        <li><a id="as-tutorial" href="{% url 'users:tutorial' %}">使用教程</a></li>
                    </ul>
                </li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    {% block main_content %}
    {% endblock %}
    <!--main content end-->
    <!--footer start-->
    <footer class="site-footer">
        <div class="text-center">
            <p>
                &copy; powered by <strong>django</strong>.
            </p>
            <a href="index.html#" class="go-top">
                <i class="fa fa-angle-up"></i>
            </a>
        </div>
    </footer>
    <!--footer end-->
</section>
<!-- js placed at the end of the document so the pages load faster -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>

<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>
<script class="include" type="text/javascript" src="{% static "lib/jquery.dcjqaccordion.2.7.js" %}"></script>
<script src="{% static "lib/jquery.scrollTo.min.js" %}"></script>
<script src="{% static "lib/jquery.nicescroll.js" %}" type="text/javascript"></script>
<script src="{% static "lib/jquery.sparkline.js" %}"></script>
<!--common script for all pages-->
<script src="{% static "lib/common-scripts.js" %}"></script>
<script type="text/javascript" src="{% static "lib/gritter/js/jquery.gritter.js" %}"></script>
<script type="text/javascript" src="{% static "lib/gritter-conf.js" %}"></script>
<!--script for this page-->
<script src="{% static "lib/sparkline-chart.js" %}"></script>
<script src="{% static "lib/zabuto_calendar.js" %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var title = $(document).attr("title");
        if (title === "SSRMGMT-系统") {
            $('#as-system').addClass("active");
        } else if (title === "SSRMGMT-用户中心") {
            $('#as-my').addClass("active");
            $('#as-my').click();
            $('#as-center').parent().addClass("active");
        } else if (title === "SSRMGMT-账户资料") {
            $('#as-my').addClass("active");
            $('#as-my').click();
            $('#as-account').parent().addClass("active");
        } else if (title === "SSRMGMT-资料编辑") {
            $('#as-my').addClass("active");
            $('#as-my').click();
            $('#as-edit').parent().addClass("active");
        } else if (title === "SSRMGMT-用户工单") {
            $('#as-my').addClass("active");
            $('#as-my').click();
            $('#as-workorder').parent().addClass("active");
        } else if (title === "SSRMGMT-答题赚取硬币") {
            $('#as-coin').addClass("active");
            $('#as-coin').click();
            $('#as-answer').parent().addClass("active");
        } else if (title === "SSRMGMT-邀请赚取硬币") {
            $('#as-coin').addClass("active");
            $('#as-coin').click();
            $('#as-invite').parent().addClass("active");
        } else if (title === "SSRMGMT-购买时长") {
            $('#as-buy').addClass("active");
            $('#as-buy').click();
            $('#as-time').parent().addClass("active");
        } else if (title === "SSRMGMT-购买记录") {
            $('#as-buy').addClass("active");
            $('#as-buy').click();
            $('#as-record').parent().addClass("active");
        } else if (title === "SSRMGMT-节点列表") {
            $('#as-use').addClass("active");
            $('#as-use').click();
            $('#as-list').parent().addClass("active");
        } else if (title === "SSRMGMT-节点详情") {
            $('#as-use').addClass("active");
            $('#as-use').click();
            $('#as-list').parent().addClass("active");
        }
        else if (title === "SSRMGMT-使用教程") {
            $('#as-use').addClass("active");
            $('#as-use').click();
            $('#as-tutorial').parent().addClass("active");
        } else if (title === "SSRMGMT-修改节点") {

        }
    });
</script>
{% block otherscript %}{% endblock %}
</body>
</html>

templates/backend/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SSRMGMT-首页</title>

    <link href="{% static "img/favicon.png" %}" rel="icon">
    <!-- Bootstrap Core CSS -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/stylish-portfolio.css" %}" rel="stylesheet">
    <style type="text/css">
        .header {
            display: table;
            position: fixed;
            width: 100%;
            height: 100%;
            background: url({% static "img/bg.jpg" %}) no-repeat center center scroll;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            background-size: cover;
            -o-background-size: cover;
        }

        @font-face {
            font-family: 'FontAwesome';
            src: url("{% static "fonts/fontawesome-webfont.eot?v=4.3.0" %}");
            src: url("{% static "fonts/fontawesome-webfont.eot?#iefix&v=4.3.0" %}") format('embedded-opentype'), url("{% static "fonts/fontawesome-webfont.woff2?v=4.3.0" %}") format('woff2'), url("{% static "fonts/fontawesome-webfont.woff?v=4.3.0" %}") format('woff'), url("{% static "fonts/fontawesome-webfont.ttf?v=4.3.0" %}") format('truetype'), url("{% static "fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular" %}") format('svg');
            font-weight: normal;
            font-style: normal;
        }
    </style>

    <!-- Custom Fonts -->
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <!--<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand">
            <a href="#" onclick=$("#menu-close").click();>Hello!</a>
        </li>
        <li>
            <a href="#" onclick=$("#menu-close").click();>就当</a>
        </li>
        <li>
            <a href="#" onclick=$("#menu-close").click();>无</a>
        </li>
        <li>
            <a href="#" onclick=$("#menu-close").click();>事</a>
        </li>
        <li>
            <a href="#" onclick=$("#menu-close").click();>发生!</a>
        </li>
    </ul>
</nav>

<!-- Header -->
<header id="top" class="header">
    <div class="text-vertical-center">
        <h1>
            <em><span class="text-warning">SSR</span></em>MGMT
        </h1>
        <h3>
            Now!
            <span class="text-danger">{{ online_node_count }}</span>个节点存活
        </h3>
        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                    <hr style="filter: alpha(opacity=100,finishopacity=0,style=3)" width="100%" color="#6f5499"
                        size="3"/>
                    <div class="col-sm-12">
                        <div class="col-sm-6">
                            <p class="text-right"><strong>用户邮箱</strong></p></div>
                        <div class="col-sm-6">
                            <p class="text-left">{{ request.user.email }}</p></div>
                    </div>
                    <div class="col-sm-12">
                        <div class="col-sm-6">
                            <p class="text-right"><strong>账号过期时间</strong></p></div>
                        <div class="col-sm-6">
                            <p class="text-left">{{ ssr.expiration_time|date:"Y-m-d H:i" }}</p></div>
                    </div>
                    <hr style="filter: alpha(opacity=100,finishopacity=0,style=3)" width="100%" color="#6f5499"
                        size="3"/>
                </div>
            </div>
        {% else %}
            <h4>测试账号：1650152108@qq.com admin12345</h4>
        {% endif %}
        <br>
        <div class="btn-group">
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:system' %}" class="btn btn-dark btn-lg">用户中心</a>
                <a href="{% url 'users:logout' %}" class="btn btn-dark btn-lg">退出登录</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-dark btn-lg">登录账户</a>
                <a href="{% url 'users:register' %}" class="btn btn-dark btn-lg">注册账户</a>
            {% endif %}
        </div>
    </div>
</header>

<!-- jQuery -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>

<!-- Custom Theme JavaScript -->
<script>
    // Closes the sidebar menu
    $("#menu-close").click(function (e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
</script>

</body>

</html>