apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import logout
from django.conf import settings

from .views import (SendEmailCode, System, Activate, ResetPwd,
                    AccountEdit, AccountProfilePhotoModify, AccountPwdModify, AccountGeneralModify, ResetPwdEmail,
                    AccountNameModify, AccountSSRModify, AccountEmailModify, ProfileCenter,
                    WorkOrderShow, WorkOrderAdd, WorkorderView, WorkorderDelete, BuyTime, TradeRecodeShow,
                    Tutorial)

from users.utils.auth.views import ObtainJWTView, RefreshJWTView
from .views import (RegisterView, ProfileView, SSRAccountView, OnlineIPView, DataUsageView,
                    ProfilePhotoView)

urlpatterns = [
    path('login/', ObtainJWTView.as_view(), name='login'),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name="logout"),
    path('refresh/', RefreshJWTView.as_view()),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('ssr/', SSRAccountView.as_view(), name='ssr'),
    path('onlineip/', OnlineIPView.as_view(), name='onelineip'),
    path('datausage/', DataUsageView.as_view(), name='datausage'),
    path('profilephoto/', ProfilePhotoView.as_view(), name='profilephoto'),

    path('resetpwd/', ResetPwd.as_view(), name='resetpwd'),
    path('resetpwdemail/', ResetPwdEmail.as_view(), name='resetpwdemail'),
    path('system/', System.as_view(), name='system'),
    path('profile/send-mail', SendEmailCode.as_view(), name='send_mail'),
    path('profile/account_edit', AccountEdit.as_view(), name='account_edit'),
    path('account/profile_photo_modify', AccountProfilePhotoModify.as_view(), name="photo_modify"),
    path('account/modify-pwd', AccountPwdModify.as_view(), name='modify-pwd'),
    path('account/modify-general', AccountGeneralModify.as_view(), name='modify-general'),
    path('account/modify-username', AccountNameModify.as_view(), name='modify-username'),
    path('account/modify-ssr', AccountSSRModify.as_view(), name='modify-ssr'),
    path('account/modify-email', AccountEmailModify.as_view(), name='modify-email'),
    path('profile/center', ProfileCenter.as_view(), name='profile-center'),
    path('workorder/show', WorkOrderShow.as_view(), name='workorder-show'),
    path('workorder/add', WorkOrderAdd.as_view(), name='workorder-add'),
    path('workorder/delete/<int:wo_id>', WorkorderDelete.as_view(), name='workorder-delete'),
    path('workorder/view/<int:wo_id>', WorkorderView.as_view(), name='workorder-view'),
    path('buy/time', BuyTime.as_view(), name='buy-time'),
    path('buy/recordshow', TradeRecodeShow.as_view(), name='record-show'),
    path('usage/tutorial/', Tutorial.as_view(), name='tutorial')
]

ssrmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from users.views import Index, Activate
# from ssrmgmt.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('activate/', Activate.as_view()),
    path('api/<str:version>/', include(('users.urls', 'users'), namespace='users')),
    path('api/<str:version>/', include(('API.urls', 'API'), namespace='api')),
    path('api/<str:version>/', include(('node.urls', 'node'), namespace='node')),
    path('', Index.as_view(), name='index'),
    # 创建一个命名空间，可以有效的对url进行分类
    # path('users/', include(("users.urls", "users"), namespace="users")),
    # path('api/', include(("API.urls", "API"), namespace="api")),
    # path('node/', include(("node.urls", "node"), namespace="node")),
    # path('media/<str>', serve, {"document_root": MEDIA_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>SSRMGMT-登录</title>

    <!-- Favicons -->
    <link href="{% static "img/favicon.png" %}" rel="icon">
    <link href="{% static "img/apple-touch-icon.png" %}" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static "lib/font-awesome/css/font-awesome.css" %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
</head>

<body>
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<div id="login-page">
    <div class="container">
        <form class="form-login" action="{% url 'users:login' %}" method="post">
            <h2 class="form-login-heading">登入</h2>
            <div class="login-wrap">
                <input type="text" class="form-control" placeholder="Email or User ID"
                       name="username" value="" autofocus>
                <br>
                <input type="password" class="form-control" placeholder="Password" name="password" value="">
                <label class="checkbox">
                    <!--<input type="checkbox" value="remember-me"> Remember me-->
                    <span class="pull-right">
                        <a data-toggle="modal" href="login.html#myModal"> 忘记密码?</a>
                    </span>
                </label>
                <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i> 登录
                </button>
                {% csrf_token %}
                {% if result != None %}
                    <br>
                    <div class="alert alert-warning alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>失败!</strong> {{ result }}
                    </div>
                {% endif %}
                <hr>
                <div class="registration">
                    还没有账户?<br/>
                    <a class="" href="#">
                        现在注册
                    </a>
                </div>
            </div>
            <!-- Modal -->
            <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal"
                 class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">忘记密码 ?</h4>
                        </div>
                        <div class="modal-body">
                            <p>输入注册邮箱去重置密码.</p>
                            <input type="text" name="email" placeholder="Email" autocomplete="off" id="email"
                                   class="form-control placeholder-no-fix">
                        </div>
                        <div class="modal-footer">
                            <button data-dismiss="modal" class="btn btn-default" type="button">取消</button>
                            <button class="btn btn-theme" type="button" id="sendmail">提交</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- modal -->
        </form>
    </div>
</div>
<!-- js placed at the end of the document so the pages load faster -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>
<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>
<!--BACKSTRETCH-->
<!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
<script type="text/javascript" src="{% static "lib/jquery.backstretch.min.js" %}"></script>
<script>
    $.backstretch("{% static "img/bg-login.png" %}", {
        speed: 500
    });
</script>
<script>
        $(function () {
            //修改一般信息
            $('#sendmail').click(function () {
                csrf = '{{ csrf_token }}';
                email = $('#email').val();
                //发起ajax请求，注意csrf攻击
                $.post("{% url 'users:resetpwdemail' %}", {
                    'csrfmiddlewaretoken': csrf,
                    'email': email
                }, function (data) {
                    //获取返回的数据并进行操作
                    alert(data.res);
                })
            });
        });
    </script>
</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>SSRMGMT-注册</title>

    <!-- Favicons -->
    <link href="{% static "img/favicon.png" %}" rel="icon">
    <link href="{% static "img/apple-touch-icon.png" %}" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static "lib/font-awesome/css/font-awesome.css" %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
</head>

<body>
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<div id="login-page">
    <div class="container">
        <form class="form-login" action="{% url 'users:register' %}" method="post">
            <h2 class="form-login-heading">注册</h2>
            <!--表明这个表单是注册用的-->
            <input type="hidden" value="register" id="email_type">
            <div class="login-wrap">
                <input type="text" class="form-control" placeholder="Email"
                       name="email" value="" id="email" autofocus>
                <br>
                <!--<button class="btn btn-theme btn-send">-->
{#                <div class="form-inline">#}
{#                    <input type="text" class="form-control" id="verify_code" name="verify_code" value=""#}
{#                           placeholder="Verify Code">#}
{#                    <div class="input-group-append">#}
{#                        <button class="btn btn-secondary left-side" type="button" id="send_mail">获取验证码</button>#}
{#                    </div>#}
{#                </div>#}
{#                <br>#}
                <input type="password" class="form-control" placeholder="Password" name="password" value="">
                <br>
                <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i> 注册
                </button>
                <br>
                <div class="alert alert-success hidden" id="status">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong id="result"></strong>
                </div>
                {% if result != None %}
                    {% if result == '注册成功' %}
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert">x</button>
                            <strong>成功!</strong> {{ result }}
                        </div>
                    {% else %}
                        <div class="alert alert-warning alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert">x</button>
                            <strong>失败!</strong> {{ result }}
                        </div>
                    {% endif %}
                {% endif %}
                <hr>
                <div class="registration">
                    已经有账号?<br/>
                    <a class="" href="{% url 'users:login' %}">
                        现在登录
                    </a>
                </div>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>
<!-- js placed at the end of the document so the pages load faster -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>
<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>
<!--BACKSTRETCH-->
<!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
<script type="text/javascript" src="{% static "lib/jquery.backstretch.min.js" %}"></script>
<script>
    $.backstretch("{% static "img/bg-register.jpg" %}", {
        speed: 500
    });
</script>
<script>
    $(function () {
        $('#send_mail').click(function () {
            csrf = $("input[name='csrfmiddlewaretoken']").val();
            email = $('#email').val();
            email_type = $('#email_type').val();
            {#alert(csrf + email + email_type)#}
            //发起ajax请求，注意csrf攻击
            $.post("{% url 'users:send_mail' %}", {
                'csrfmiddlewaretoken': csrf,
                'email': email,
                'email_type': email_type
            }, function (data) {
                //获取返回的数据并进行操作
                if (data.res === 'success') {
                    //邮箱验证码发送成功
                    $('#status').attr("class", "alert alert-success alert-dismissable");
                    $('#status').text("发送成功");
                    $('#status').attr('class').removeTag("hidden");
                    $('#result').text("成功！");
                } else if (data.res === 'resend') {
                    $('#status').attr("class", "alert alert-warning alert-dismissable");
                    $('#status').text("请勿重复发送");
                    $('#result').text("警告！");
                } else if (data.res === 'fail') {
                    $('#status').attr("class", "alert alert-warning alert-dismissable");
                    $('#status').text("验证码发送失败");
                    $('#result').text("失败！");
                } else if (data.res === 'unknown') {
                    $('#status').attr("class", "alert alert-warning alert-dismissable");
                    $('#status').text("请稍后再试");
                    $('#result').text("未知！");
                } else if (data.res === 'already_existed') {
                    $('#status').attr("class", "alert alert-warning alert-dismissable");
                    $('#status').text("邮箱已经存在");
                    $('#result').text("未知！");
                }
            })
        });
    });
</script>
</body>

</html>

templates/resetpwd.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>SSRMGMT-登录</title>

    <!-- Favicons -->
    <link href="{% static "img/favicon.png" %}" rel="icon">
    <link href="{% static "img/apple-touch-icon.png" %}" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static "lib/font-awesome/css/font-awesome.css" %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
</head>

<body>
<!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
<div id="login-page">
    <div class="container">
        <form class="form-login" action="{% url 'users:resetpwd' %}" method="post">
            <h2 class="form-login-heading">重置密码</h2>
            <div class="login-wrap">
                <input type="password" class="form-control" placeholder="New Password"
                       name="password1" value="" autofocus>
                <br>
                <input type="password" class="form-control" placeholder="New Password"
                       name="password2" value="">
                <input type="hidden" class="form-control" name="email" value={{ email }}>
                <input type="hidden" class="form-control" name="code" value={{ code }}>
                <label class="checkbox">
                    <span class="pull-right"></span>
                </label>
                <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-check"></i> 确认重置
                </button>
                {% csrf_token %}
                {% if result != None %}
                    <br>
                    <div class="alert alert-warning alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>失败!</strong> {{ result }}
                    </div>
                {% endif %}
                <div class="registration">
                    <a class="" href="{% url 'users:login' %}">
                        现在登录？
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- js placed at the end of the document so the pages load faster -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>
<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>
<!--BACKSTRETCH-->
<!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
<script type="text/javascript" src="{% static "lib/jquery.backstretch.min.js" %}"></script>
<script>
    $.backstretch("{% static "img/bg-login.png" %}", {
        speed: 500
    });
</script>

</body>

</html>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SSRMGMT-用户激活</title>
</head>
<body>
<h2>{{ result }}</h2>
</body>
</html>