apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import logout
from django.conf import settings

from .views import (SendEmailCode, System, Activate, ResetPwd,
                    AccountEdit, AccountProfilePhotoModify, AccountPwdModify, AccountGeneralModify, ResetPwdEmail,
                    AccountNameModify, AccountSSRModify, AccountEmailModify, ProfileCenter,
                    WorkOrderShow, WorkOrderAdd, WorkorderView, WorkorderDelete, BuyTime, TradeRecodeShow,
                    Tutorial)

from users.utils.auth.views import ObtainJWTView, RefreshJWTView
from .views import (RegisterView, ProfileView, SSRAccountView, OnlineIPView, DataUsageView,
                    ProfilePhotoView)

urlpatterns = [
    path('login/', ObtainJWTView.as_view(), name='login'),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name="logout"),
    path('refresh/', RefreshJWTView.as_view()),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('ssr/', SSRAccountView.as_view(), name='ssr'),
    path('onlineip/', OnlineIPView.as_view(), name='onelineip'),
    path('datausage/', DataUsageView.as_view(), name='datausage'),
    path('profilephoto/', ProfilePhotoView.as_view(), name='profilephoto'),

    path('resetpwd/', ResetPwd.as_view(), name='resetpwd'),
    path('resetpwdemail/', ResetPwdEmail.as_view(), name='resetpwdemail'),
    path('system/', System.as_view(), name='system'),
    path('profile/send-mail', SendEmailCode.as_view(), name='send_mail'),
    path('profile/account_edit', AccountEdit.as_view(), name='account_edit'),
    path('account/profile_photo_modify', AccountProfilePhotoModify.as_view(), name="photo_modify"),
    path('account/modify-pwd', AccountPwdModify.as_view(), name='modify-pwd'),
    path('account/modify-general', AccountGeneralModify.as_view(), name='modify-general'),
    path('account/modify-username', AccountNameModify.as_view(), name='modify-username'),
    path('account/modify-ssr', AccountSSRModify.as_view(), name='modify-ssr'),
    path('account/modify-email', AccountEmailModify.as_view(), name='modify-email'),
    path('profile/center', ProfileCenter.as_view(), name='profile-center'),
    path('workorder/show', WorkOrderShow.as_view(), name='workorder-show'),
    path('workorder/add', WorkOrderAdd.as_view(), name='workorder-add'),
    path('workorder/delete/<int:wo_id>', WorkorderDelete.as_view(), name='workorder-delete'),
    path('workorder/view/<int:wo_id>', WorkorderView.as_view(), name='workorder-view'),
    path('buy/time', BuyTime.as_view(), name='buy-time'),
    path('buy/recordshow', TradeRecodeShow.as_view(), name='record-show'),
    path('usage/tutorial/', Tutorial.as_view(), name='tutorial')
]

ssrmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from users.views import Index, Activate
# from ssrmgmt.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('activate/', Activate.as_view()),
    path('api/<str:version>/', include(('users.urls', 'users'), namespace='users')),
    path('api/<str:version>/', include(('API.urls', 'API'), namespace='api')),
    path('api/<str:version>/', include(('node.urls', 'node'), namespace='node')),
    path('', Index.as_view(), name='index'),
    # 创建一个命名空间，可以有效的对url进行分类
    # path('users/', include(("users.urls", "users"), namespace="users")),
    # path('api/', include(("API.urls", "API"), namespace="api")),
    # path('node/', include(("node.urls", "node"), namespace="node")),
    # path('media/<str>', serve, {"document_root": MEDIA_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend/my/center.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-用户中心</title>
{% endblock %}

{% block other_link %}
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper site-min-height">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="custom-box">
                            <div class="servicetitle">
                                <h4>SS信息</h4>
                                <hr>
                            </div>
                            <img src="{{ ssr_account.ss_qrcode }}" class="img-responsive center-block" width="200"
                                 height="200">
                            <div id="sslink" style="word-break:break-all; word-wrap:break-word;">
                                <p>{{ ssr_account.ss_url }}</p>
                            </div>
                            <ul class="pricing">
                                <li>{{ ssr_account.method }}</li>
                                <li>{{ ssr_account.protocol }}</li>
                                <li>{{ ssr_account.obfs }}</li>
                            </ul>
                            <a class="btn btn-theme" onclick="copy('sslink')">复制SS链接</a>
                        </div>
                        <!-- end custombox -->
                    </div>
                    <!-- end col-4 -->
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="custom-box">
                            <div class="servicetitle">
                                <h4>SSR信息</h4>
                                <hr>
                            </div>
                            <img src="{{ ssr_account.ssr_qrcode }}" class="img-responsive center-block" width="200"
                                 height="200">
                            <div id="ssrlink" style="word-break:break-all; word-wrap:break-word;">
                                <p>{{ ssr_account.ssr_url }}</p>
                            </div>
                            <ul class="pricing">
                                <li>{{ ssr_account.method }}</li>
                                <li>{{ ssr_account.protocol }}</li>
                                <li>{{ ssr_account.obfs }}</li>
                            </ul>
                            <a class="btn btn-theme" onclick="copy('ssrlink')">复制SSR链接</a>
                        </div>
                        <!-- end custombox -->
                    </div>
                </div>
                <!--  /col-lg-12 -->
                <div class="col-lg-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="content-panel">
                            <table class="table table-striped table-advance table-hover">
                                <h4><i class="fa fa-angle-right"></i> 当前账户在线IP统计 </h4>
                                <hr>
                                <thead>
                                <tr>
                                    <th><i class="fa fa-clock-o"></i> IP</th>
                                    <th><i class="fa fa-desktop"></i> 归属地</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ip, area in ip_info.items %}
                                    <tr>
                                        <td>{{ ip }}</td>
                                        <td>{{ area }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <p></p>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="content-panel">
                            <h4><i class="fa fa-angle-right"></i> 账号流量使用 </h4>
                            <div class="panel-body">
                                <div id="hero-area" class="graph"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--  /row -->
        </section>
        <!-- /wrapper -->
    </section>
{% endblock %}

{% block otherscript %}
    <script src="{% static "lib/raphael/raphael.min.js" %}"></script>
    <script src="{% static "lib/morris/morris.min.js" %}"></script>
    <script type="text/javascript">
        //复制标签中的内容，被复制的标签不能隐藏
        function copy(id) {
            var val = document.getElementById(id);
            window.getSelection().selectAllChildren(val);
            document.execCommand("Copy");
        }
    </script>
    <script type="text/javascript">
        var Script = function () {
            $(function () {
                Morris.Area({
                    element: 'hero-area',
                    data: [
                        {% for data in usages %}
                            {
                                day: "{{ data.x|date:"Y-m-d" }}",
                                download: {{ data.yd }},
                                upload: {{ data.yu }},
                                total: {{data.yd}}+{{ data.yu }}
                            },
                        {% endfor %}
                    ],
                    xkey: 'day',
                    ykeys: ['download', 'upload', 'total'],
                    labels: ['下载(m)', '上传(m)', '总使用(m)'],
                    /*xLabelFormat: function (d) {
                        if (d.day % 3 === 0) {
                            return d
                        } else {
                            return ""
                        }
                    },*/
                    //xLabelAngle: 45,
                    hideHover: 'auto',
                    lineWidth: 1,
                    pointSize: 5,
                    lineColors: ['#4a8bc2', '#ff6c60', '#a9d86e'],
                    fillOpacity: 0.5,
                    smooth: true,
                    parse_time: false
                });
                $('.code-example').each(function (index, el) {
                    eval($(el).text());
                });
            });
        }();
    </script>
{% endblock %}

templates/backend/my/profile.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}<title>SSRMGMT-账户资料</title>{% endblock %}

{% block main_content %}
    <!--main content start-->
    <!-- /MAIN CONTENT -->
    <section id="main-content">
        <section class="wrapper site-min-height">
            <div class="row mt">
                <div class="col-lg-12">
                    <div class="row content-panel">
                        <div class="col-md-4 profile-text mt mb centered">
                            <div class="right-divider hidden-sm hidden-xs">
                                <h4>{{ level }}</h4>
                                <h6>等级</h6>
                                <h4>{{ request.user.coin_nums }}</h4>
                                <h6>硬币数</h6>
                                {% if request.user.birthday %}
                                    <h4>{{ request.user.birthday|date:'Y-m-d' }}</h4>
                                {% else %}
                                    <h4>None</h4>
                                {% endif %}

                                <h6>生日</h6>
                            </div>
                        </div>
                        <!-- /col-md-4 -->
                        <div class="col-md-4 profile-text">
                            <h3>{{ request.user.username }}</h3>
                            <h6>注册用户</h6>
                            <h3>{{ request.user.mobile }}</h3>
                            <h6>Mobile</h6>
                            <h3>{{ request.user.email }}</h3>
                            <h6>Email</h6>
                        </div>
                        <!-- /col-md-4 -->
                        <div class="col-md-4 centered">
                            <div class="profile-pic">
                                <p><img src="{{ MEDIA_URL }}{{ request.user.profile_photo }}" class="img-circle"></p>
                            </div>
                            <div class="profile-text">
                                <h3>{{ request.user.username }}</h3>
                            </div>
                        </div>
                        <!-- /col-md-4 -->
                    </div>
                    <!-- /row -->
                </div>
                <!-- /col-lg-12 -->
                <div class="col-lg-12 mt">
                    <div class="row content-panel">
                        <div class="panel-body">
                            <div class="tab-content">
                                <div id="overview" class="tab-pane active">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="detailed mt">
                                                <h4>地址</h4>
                                                <div class="activity-panel">
                                                    <p>{{ request.user.address }}</p>
                                                </div>
                                            </div>
                                            <!-- /detailed -->
                                        </div>
                                    </div>
                                    <!-- /OVERVIEW -->
                                </div>
                                <!-- /tab-pane -->
                            </div>
                            <!-- /tab-content -->
                        </div>
                        <!-- /panel-body -->
                    </div>
                    <!-- /col-lg-12 -->
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </section>
        <!-- /wrapper -->
    </section>
    <!--main content end-->
{% endblock %}

templates/backend/my/workorder.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-用户工单</title>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <!-- row -->
            <div class="row mt">
                <div class="col-md-12">
                    <div class="content-panel">
                        <table class="table table-striped table-advance table-hover">
                            <h4><i class="fa fa-angle-right"></i> 工单 </h4>
                            <hr>
                            <thead>
                            <tr>
                                <th><i class="fa fa-clock-o"></i> 提交时间</th>
                                <th><i class="fa fa-bookmark"></i> 标题</th>
                                <th><i class=" fa fa-edit"></i> 状态</th>
                                <th class="hidden-phone"><i class="fa fa-question-circle"></i> 详细</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in workorder %}
                                <tr>
                                    <td>{{ order.add_time|date:"Y-m-d H:i:s" }}</td>
                                    <td class="hidden-phone"><a
                                            href="{% url 'users:workorder-view' order.id %}">{{ order.title|truncatewords:"15" }}</a>
                                    </td>
                                    <td>
                                        {% if order.status == "open" %}
                                            <span class="label label-danger label-mini">OPEN</span>
                                        {% else %}
                                            <span class="label label-success label-mini">CLOSED</span>
                                        {% endif %}
                                    </td>
                                    <td><a type="button" class="btn btn-info btn-xs"
                                           href={% url 'users:workorder-view' order.id %}>desc</a></td>
                                    <td>
                                        <button class="btn btn-danger btn-xs"
                                                onclick="del_wo('{% url 'users:workorder-delete' order.id %}')">
                                            <i class="fa fa-trash-o "></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <a type="button" class="btn btn-theme " href="{% url 'users:workorder-add' %}">
                            <i class="fa fa-plus"></i>添加工单
                        </a>
                    </div>
                    <!-- /content-panel -->
                </div>
                <!-- /col-md-12 -->
            </div>
            <!-- /row -->
        </section>
    </section>
{% endblock %}

{% block otherscript %}
    <script>
        function del_wo(url) {
            csrf = '{{ csrf_token }}';
            //发起ajax请求，注意csrf攻击
            $.get(url,
                function (data) {
                    //获取返回的数据并进行操作
                    alert(data.res);
                })
        }
    </script>
{% endblock %}

templates/backend/my/workorder_add.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-用户工单</title>
{% endblock %}

{% block other_link %}
    <link href="{% static "lib/bootstrap-wysihtml5/bootstrap-wysihtml5.css" %}" rel="stylesheet"/>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <!-- page start-->
            <div class="row mt">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading wht-bg">
                            <h4 class="gen-case">
                                提交工单
                            </h4>
                        </header>
                        <div class="panel-body">
                            <div class="compose-mail">
                                <form role="form-horizontal">
                                    <div class="form-group">
                                        <label for="subject" class="">Title:</label>
                                        <input type="text" tabindex="1" id="text_title" class="form-control">
                                    </div>
                                    <div class="compose-editor">
                                        <textarea class="wysihtml5 form-control" rows="9" id="text_body"></textarea>
                                    </div>
                                    <div class="compose-btn">
                                        <button class="btn btn-theme btn-sm" id="wo_add" type="button"><i class="fa fa-check"></i> 提交</button>
                                        <button class="btn btn-sm"><i class="fa fa-times"></i> Discard</button>
                                        <button class="btn btn-sm">Draft</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /wrapper -->
    </section>
{% endblock %}

{% block otherscript %}
    <script>
        $(function () {
            //修改账号密码
            $('#wo_add').click(function () {
                csrf = '{{ csrf_token }}';
                body = $('#text_body').val();
                title = $('#text_title').val();
                //发起ajax请求，注意csrf攻击
                $.post("{% url 'users:workorder-add' %}", {
                    'csrfmiddlewaretoken': csrf,
                    'body': body,
                    'title': title
                }, function (data) {
                    //获取返回的数据并进行操作
                    alert(data.res);
                })
            });
        });
    </script>
    <script type="text/javascript" src="{% static "lib/bootstrap-wysihtml5/wysihtml5-0.3.0.js" %}"></script>
    <script type="text/javascript" src="{% static "lib/bootstrap-wysihtml5/bootstrap-wysihtml5.js" %}"></script>
    <script type="text/javascript">
        //wysihtml5 start
        $('.wysihtml5').wysihtml5();
        //wysihtml5 end
    </script>
{% endblock %}

templates/backend/my/workorder_view.html
{% extends 'backend/bebase.html' %}
{% load static %}

{% block title %}
    <title>SSRMGMT-用户工单</title>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <!-- page start-->
            <div class="row mt">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading wht-bg">
                            <h4>
                                详细工单
                            </h4>
                        </header>
                        <div class="panel-body ">
                            <div class="mail-sender">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h4 class="pull-left"> {{ workorder.title }} </h4>
                                    </div>
                                    <div class="col-md-4">
                                        <p class="date"> {{ workorder.add_time|date:"Y-m-d H:i:s" }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="view-mail">
                                {{ workorder.body|safe  }}
                            </div>
                            <div class="compose-btn pull-left">
                                <a href="{% url 'users:workorder-show' %}" class="btn btn-sm btn-theme"><i class="fa fa-reply"></i>
                                    返回</a>
                                <button class="btn btn-sm "><i class="fa fa-arrow-right"></i> Forward</button>
                                <button class="btn  btn-sm tooltips" data-original-title="Print" type="button"
                                        data-toggle="tooltip" data-placement="top" title=""><i class="fa fa-print"></i>
                                </button>
                                <button class="btn btn-sm tooltips" data-original-title="Trash" data-toggle="tooltip"
                                        data-placement="top" title=""><i class="fa fa-trash-o"></i></button>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /wrapper -->
    </section>
{% endblock %}